Graph:
  NotebookName: Trash
  SectionName: "Book 5"
  RefreshPages: False
  EnvPath:
  PageLimit:  # number(s) or empty
Emotions:
  Quantize: False
  ModelPath:
    Default: /Users/ykamoji/Documents/open-ai-maya-audio-generation/models/models-llama-quantized/llama-3.1-8b-q2_K.gguf
    Kaggle: # For Kaggle, use internal cache
    Colab: /content/open-ai-maya-audio-generation/Models/
Generator:
  PageLimit:  4 # number(s) or empty
  PageNo:
  SkipTitleGeneration: False
  AudioOutputPath:
    Default: output/
    Kaggle: /kaggle/working/output/
    Colab: /content/drive/MyDrive/AI/Outputs/
  GPU:
    Default: 0
    Kaggle: 2
    Colab: 1
  OpenAI:
    Action: False
    ChunkLimit: 1000
  Maya:
    Action: True
    ModelPath:
      Default: /Users/ykamoji/Documents/open-ai-maya-audio-generation/models/
      Kaggle: # For Kaggle, use internal cache
      Colab: /content/drive/MyDrive/AI/Models/
    Characters:
      - Name: David
        Description: "Seductively character, Male voice in their 30s with American accent. Low pitch, gravelly timbre, slow pacing, casual tone at mid intensity"
      - Name: Vanessa
        Description: "Seductively character, Female voice in their 30s with American accent. Low pitch, gravelly timbre, slow pacing, casual tone at mid intensity"
      - Name: Blake
        Description: "Realistic dramatic narrator character, Male voice in their 30s with a American accent. Low pitch, gravelly timbre, slow pacing, casual tone at mid intensity"
