Graph:
  NotebookName: Trash
  SectionName: "Book 5"
  RefreshPages: False
  EnvPath:
  PageLimit:  # number(s) or empty
Emotions:
  Quantize: False
  ModelName:
    Default: meta-llama/Llama-3.1-8B-Instruct
    Kaggle: /kaggle/input/llama-3-1-8b-instruct/transformers/1/1/
    Colab: meta-llama/Llama-3.1-8B-Instruct
  CachePath:
    Default: /Users/ykamoji/Documents/open-ai-maya-audio-generation/models/
    Kaggle: /kaggle/working/output/
    Colab: /content/open-ai-maya-audio-generation/Models/
Generator:
  PageLimit:  # [start, end]
  PageNums: # [numbers] or empty
  AudioOutputPath:
    Default: output/
    Kaggle: /kaggle/working/output/
    Colab: /content/drive/MyDrive/AI/Outputs/
  GPU:
    Default: 0
    Kaggle: 2
    Colab: 1
  OpenAI:
    Action: False
    ChunkLimit: 1000
  Maya:
    Action: True
    ModelName:
      Default: maya-research/maya1
      Kaggle: /kaggle/input/maya/transformers/1/2/
      Colab: maya-research/maya1
    CachePath:
      Default: /Users/ykamoji/Documents/open-ai-maya-audio-generation/models/
      Kaggle: /kaggle/working/output/
      Colab: /content/drive/MyDrive/AI/Models/
    Characters:
      - Name: David
        Description: "Creative, seductively character. Male voice in their 30s with american accent. Low pitch, smooth timbre, slow pacing, neutral tone at high intensity." # 1.25x
      - Name: Vanessa
        Description: "Creative, seductively character. Female voice in their 30s with american accent. Low pitch, raspy timbre, slow pacing, casual tone at low intensity." # 1.25x
      - Name: Blake
        Description: "Creative, dramatic_narrator character. Male voice in their 30s with american accent. Low pitch, warm timbre, very slow pacing, casual tone at mid intensity." # 1.25x
