Graph:
  NotebookName: Trash
  SectionName: "Book 5"
  RefreshPages: False
  EnvPath:
  PageLimit:  2 # number(s) or empty
Emotions:
  Quantize: False
  ModelPath:
    Default: /Users/ykamoji/Documents/open-ai-maya-audio-generation/models/
    Kaggle: # For Kaggle, use internal cache
    Colab: /content/open-ai-maya-audio-generation/Models/
Generator:
  PageLimit:  2 # number(s) or empty
  PageNo:
  AudioOutputPath:
    Default: output/
    Kaggle: /kaggle/working/output/
    Colab: /content/drive/MyDrive/AI/Outputs/
  GPU:
    Default: 0
    Kaggle: 2
    Colab: 1
  OpenAI:
    Action: False
    ChunkLimit: 1000
  Maya:
    Action: True
    ModelPath:
      Default: /Users/ykamoji/Documents/open-ai-maya-audio-generation/models/
      Kaggle: # For Kaggle, use internal cache
      Colab: /content/drive/MyDrive/AI/Models/
    Characters:
      - Name: David
        Description: "Seductively character, Male voice in their 30s with a American accent. normal pitch, gravelly timbre, brisk pacing, casual tone at mid intensity"
      - Name: Vanessa
        Description: "Seductively character, Female voice in their 30s with a American accent. low pitch, deep timbre, brisk pacing, casual tone at mid intensity"
      - Name: Blake
        Description: "Dark villain character, Male voice in their 30s with a American accent. normal pitch, gravelly timbre, brisk pacing, casual tone at mid intensity"
